// one day we'll redo this shitty categories
DefaultCategories = [
    "Life as Superman",
    "3 bad names for Hair Salons",
    "Whose got the beer?",
    "Interview Responses",
    "Candy Bars",
    "kickball",
    "Knock knock ... who's there?",
    "Bad tattoo ideas",
    "Signs that you lost the argument",
    "Bad Fairy Tale Endings",
    "Rhyme time",
    "Workaholics",
    "Dumbest star in Hollywood",
    "We got divorced because ...",
    "4 words, similar meanings",
    "Insults",
    "Bad Christmas Gifts",
    "Unpopular Toys",
    "Failed Disney Attractions",
    "General",
    "How embarrassing!",
    "Animals",
    "What's under the bed?",
    "Current Events",
    "Signs you lost the argument...",
    "Two dogs talking",
    "Fake nails",
    "1980's",
    "Chuck Norris \"Facts",
    "Where is grandma?",
    "Music",
    "The Wizzard of Oz",
    "What's that fabulous smell?",
    "How you talked yourself out of a ticket?",
    "Resolutions for New Year",
    "My mom always said ...",
    " BadPickup Lines",
    "Make it rhyme",
    "How I escaped from Alcatraz",
    "Bad breath because",
    "Why I had to tell a lie",
    "Where's the remote?",
    "Geography",
    "Rename 1derwoman",
    "What not to say to dentist",
    "2010 resolutions",
    "Rejected Ice cream flavors",
    "Lies Kids tell their Parents",
    "Favorite City",
    "Going to Jail because ...",
    "3 Red Things",
    "Chocolate",
    "Things that make you go AFK",
    "slogan for a funeral home",
    "Reality TV",
    "You may be a redneck if ...",
    "3 bad names for hookers",
    "Guilty Pleasures",
    "When I grow up ...",
    "Outrageous Wedding Vow",
    "Can't make it to work today ..",
    "whats in your wallet?",
    "Worst Date",
    "I got arrested because ...",
    "What the Fortune Teller told me ...",
    "Strangest places to ACRO",
    "Monosyllable",
    "Found in the basement",
    "Two line dialog: Husband and wife",
    "Contacted at the seance",
    "Need Counseling Because...",
    "Pet Peeves",
    "Where does your money go?",
    "Unusual birth control",
    "Games",
    "If I won the lottery",
    "What's that in the sky?",
    "Science gone awry",
    "onomatopoeia",
    "I pulled the fire alarm and...",
    "How I escaped from prison.",
    "Bad names for Mafia members",
    "Tourist Traps",
    "What's for dinner?",
    "Inlaws",
    "Health Issues",
    "Lindsay Lohan Biography Title",
    "Dude Where's My Car?",
    "The \"Truth\" about Men",
    "California",
    "Awful ways to die",
    "Dieting",
    "Bad day at driving school",
    "The Bible",
    "Rhyme",
    "Headlines",
    "Objects in space (non santa)",
    "Headlines we don't want to see",
    "Unusual Pizza toping combos",
    "Life as a secret agent",
    "Posted on YouTube",
    "Grampa Says \"In MY Day...",
    "Wimpy name for a Santa elf",
    "Zodiac Signs",
    "Family Reunions",
    "Math",
    "911. What's your emergency?",
    "Why isn't Santa coming?",
    "Literature",
    "Cartoons",
    "Mono again",
    "Grandpa says: \"In MY day..",
    "Oprah's New Game Show",
    "Bad Country Song Titles",
    "Bad day at driving school.",
    "What to say to an ex",
    "Crime TV",
    "Who is at your door?",
    "On the Farm",
    "Movies",
    "Money",
    "Desk item(s)",
    "How'd Santa fit in chimney?",
    "Acro within a Xmas acro",
    "Body Parts",
    "A + B = C",
    "stupid book titles",
    "Tough female wild-west name",
    "Santa got pulled over because.",
    "Grandpa says: \"In MY day\"...",
    "Hit songs from \"The Exorcist",
    "What dat stain on Santas lap?",
    "Awkward Situation",
    "Acro Backwards A Create",
    "nightmare",
    "Why did yu walk off a cliff?",
    "You know you're addicted to ACRO when...",
    "Mythological Creatures",
    "in the ice cave",
    "reindeer injuries",
    "Morning Routine",
    "The \"Truth\" about Women",
    "santa wrecked sleigh and",
    "Lies Parents tell their Kids",
    "what an elf eats",
    "Three words, same meaning",
    "Why you can't be President",
    "My Doctor told me",
    "Name your new business",
    "You did what?",
    "Monday mornings",
    "Redneck Christmas Gifts",
    "Make it rhyme about xmas",
    "he may be rich but....",
    "Europe",
    "Why they fired you",
    "Sea Creatures",
    "Lullaby",
    "3 Yellow Things",
    "retro videogames",
    "Family Fued (gameshow)",
    "3 Green Things",
    "Signs you might be dead:",
    "Last place you spotted Santa.",
    "a woman's things",
    "Christmas Shopping",
    "Acro backwards",
    "Breakfast Cereal",
    "What I really want for Xmas",
    "Capital punishment",
    "If you could turn back time.",
    "What Did Dan's Boss Say?",
    "In my diary ...",
    "while i was dancing i...",
    "Rock and Roll hijinx",
    "rhyme it",
    "What's the punchline?",
    "Fun things to microwave",
    "Bad hospital Names",
    "Rap Lyrics",
    "How does Santa go so fast?",
    "What's In Your Lunchbox? ",
    "Heard during childbirth",
    "Friends don't let friends...",
    "Animated TV shows",
    "Words of wisdom",
    "Yay! It's Rhyme Time again!",
    "Write something funny",
    "Bad Racehorse Names",
    "Acro backwards a RHYME",
    "How to overcome shyness",
    "What's that in your pocket?",
    "Santa's reindeer games",
    "Stuck in Traffic",
    "make up a word and define it",
    "What's in your stocking?",
    "The \"Truth\" about Your Boss!",
    "Cereal Characters",
    "Death bed Confessions",
    "Forced to choose betweeen ACRO and...",
    "Fast Food Nation",
    "Casinos",
    "Parade mishaps.",
    "Why isn't Hamburglar caught?",
    "sugarplums",
    "Drinking like a Fish",
    "Why you got a Nobel Prize",
    "Musical Instruments",
    "__________. High five, bro.",
    "TSA guidelines now prohibit __________ on airplanes.",
    "It's a pity that kids these days are all getting involved with __________.",
    "In 1,000 years, when paper money is but a distant memory, __________ will be our currency.",
    "Major League Baseball has banned __________ for giving players an unfair advantage.",
    "What is Batman's guilty pleasure?",
    "Next from J.K. Rowling: Harry Potter and the Chamber of __________.",
    "I'm sorry, Professor, but I couldn't complete my homework because of __________.",
    "What did I bring back from Mexico?",
    "__________? There's an app for that.",
    "Betcha can't have just one!",
    "What's my anti-drug?",
    "While the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on __________.",
    "In the new Disney Channel Original Movie, Hannah Montana struggles with __________ for the first time.",
    "What's my secret power?",
    "What's the new fad diet?",
    "What did Vin Diesel eat for dinner?",
    "When Pharaoh remained unmoved, Moses called down a Plague of __________.",
    "How am I maintaining my relationship status?",
    "What's the crustiest?",
    "When I'm in prison, I'll have __________ smuggled in.",
    "After Hurricane Katrina, Sean Penn brought __________ to the people of New Orleans.",
    "Instead of coal, Santa now gives the bad children __________.",
    "Life was difficult for cavemen before __________.",
    "What's Teach for America using to inspire inner city students to succeed?",
    "Who stole the cookies from the cookie jar?",
    "In Michael Jackson's final moments, he thought about __________.",
    "White people like __________.",
    "Why do I hurt all over?",
    "A romantic candlelit dinner would be incomplete without __________.",
    "What will I bring back in time to convince people that I am a powerful wizard?",
    "BILLY MAYS HERE FOR __________.",
    "The class field trip was completely ruined by __________.",
    "What's a girl's best friend?",
    "I wish I hadn't lost the instruction manual for __________.",
    "When I am President of the United States, I will create the Department of __________.",
    "What are my parents hiding from me?",
    "What never fails to liven up the party?",
    "What gets better with age?",
    "__________: good to the last drop.",
    "I got 99 problems but __________ ain't one.",
    "It's a trap!",
    "MTV's new reality show features eight washed-up celebrities living with __________.",
    "What would grandma find disturbing, yet oddly charming?",
    "What's the most emo?",
    "During sex, I like to think about __________.",
    "What ended my last relationship?",
    "What's that sound?",
    "__________. That's how I want to die.",
    "Why am I sticky?",
    "What's the next Happy MealÂ® toy?",
    "What's there a ton of in heaven?",
    "I do not know with what weapons World War III will be fought, but World War IV will be fought with __________.",
    "What will always get you laid?",
    "__________: kid tested, mother approved.",
    "Why can't I sleep at night?",
    "What's that smell?",
    "What helps Obama unwind?",
    "This is the way the world ends  This is the way the world ends  Not with a bang but with __________.",
    "Coming to Broadway this season, __________: The Musical.",
    "Anthropologists have recently discovered a primitive tribe that worships __________.",
    "But before I kill you, Mr. Bond, I must show you __________.",
    "Studies show that lab rats navigate mazes 50% faster after being exposed to __________.",
    "Due to a PR fiasco, Walmart no longer offers __________.",
    "When I am a billionaire, I shall erect a 50-foot statue to commemorate __________.",
    "In an attempt to reach a wider audience, the Smithsonian Museum of Natural History has opened an interactive exhibit on __________.",
    "War! What is it good for?",
    "What gives me uncontrollable gas?",
    "What do old people smell like?",
    "Sorry everyone, I just __________.",
    "Alternative medicine is now embracing the curative powers of __________.",
    "The U.S. has begun airdropping __________ to the children of Afghanistan.",
    "What does Dick Cheney prefer?",
    "During Picasso's often-overlooked Brown Period, he produced hundreds of paintings of __________.",
    "What don't you want to find in your Chinese food?",
    "I drink to forget __________.",
    "That's right, I killed __________. How, you ask? __________.",
    "And the Academy Award for __________ goes to __________.",
    "For my next trick, I will pull __________ out of __________.",
    "In his new summer comedy, Rob Schneider is __________ trapped in the body of __________.",
    "When I was tripping on acid, __________ turned into __________.",
    "__________ is a slippery slope that leads to __________.",
    "In a world ravaged by __________, our only solace is __________.",
    "In M. Night Shyamalan's new movie, Bruce Willis discovers that __________ had really been __________ all along.",
    "I never truly understood __________ until I encountered __________.",
    "Rumor has it that Vladimir Putin's favorite dish is __________ stuffed with __________.",
    "Lifetime presents __________, the story of __________.",
    "What's the next superhero/sidekick duo?"
]