/* Default header content */

export const headerMeta = [
    {
        name: "viewport",
        content: "width=device-width, initial-scale=1, user-scalable=no"
    },
    {
        name: "msapplication-TileColor",
        content: "#ffffff"
    },
    {
        name: "msapplication-TileImage",
        content: "/ms-icon-144x144.png"
    },
    {
        name: "theme-color",
        content: "#ffffff"
    },
    {
        property: "fb:app_id",
        content: "833378536755593"
    }
];

export const headerLinks = [
    {
        href: "https://fonts.googleapis.com/css?family=Pacifico",
        rel: "stylesheet",
        type: "text/css"
    },
    {
        rel: "manifest",
        href: "/manifest.json"
    },
    {
        rel: "icon",
        type: "image/png",
        sizes: "16x16",
        href: "/favicon-16x16.png"
    },
    {
        rel: "icon",
        type: "image/png",
        sizes: "32x32",
        href: "/favicon-32x32.png"
    },
    {
        rel: "icon",
        type: "image/png",
        sizes: "96x96",
        href: "/favicon-96x96.png"
    },
    {
        rel: "icon",
        type: "image/png",
        sizes: "192x192",
        href: "/android-icon-192x192.png"
    },
    {
        rel: "apple-touch-icon",
        sizes: "57x57",
        href: "/apple-icon-57x57.png"
    },
    {
        rel: "apple-touch-icon",
        sizes: "60x60",
        href: "/apple-icon-60x60.png"
    },
    {
        rel: "apple-touch-icon",
        sizes: "72x72",
        href: "/apple-icon-72x72.png"
    },
    {
        rel: "apple-touch-icon",
        sizes: "76x76",
        href: "/apple-icon-76x76.png"
    },
    {
        rel: "apple-touch-icon",
        sizes: "114x114",
        href: "/apple-icon-114x114.png"
    },
    {
        rel: "apple-touch-icon",
        sizes: "120x120",
        href: "/apple-icon-120x120.png"
    },
    {
        rel: "apple-touch-icon",
        sizes: "144x144",
        href: "/apple-icon-144x144.png"
    },
    {
        rel: "apple-touch-icon",
        sizes: "152x152",
        href: "/apple-icon-152x152.png"
    },
    {
        rel: "apple-touch-icon",
        sizes: "180x180",
        href: "/apple-icon-180x180.png"
    }
];

// one day we'll redo this shitty categories
export const defaultCategories = [
    "Bad names for hair salons",
    "Interview responses",
    "Knock knock ... who's there?",
    "Bad tattoo ideas",
    "Signs that you lost the argument",
    "Bad Fairy Tale endings",
    "Make it rhyme!",
    "Hollywood stars in a nightmare universe",
    "We got divorced because...",
    "Words with similar meanings",
    "Insults",
    "Bad Christmas gifts",
    "Unpopular Toys",
    "Failed Disney attractions",
    "General",
    "Embarrassing moments",
    "Things that make you cringe",
    "Bizarre animals",
    "Current events",
    "Too soon...",
    "What a dog would say if it were human",
    "1980s",
    "1990s",
    "2000s",
    "1970s",
    "Only 90s kids remember this",
    "Chuck Norris \"Facts\"",
    "What's Grandma up to?",
    "Music",
    "What's that fabulous smell?",
    "How you talked yourself out of a ticket",
    "Resolutions for the New Year",
    "My Mother always said...",
    "Bad pickup lines",
    "How I escaped from prison",
    "Bad breath because...",
    "Why I had to tell a lie",
    "What not to say to dentist",
    "Rejected ice cream flavors",
    "Lies kids tell their parents",
    "Going to prison because ...",
    "Things that make you go AFK",
    "Slogan for a funeral home",
    "Reality TV",
    "You may be a redneck if ...",
    "Bad names for hookers",
    "Guilty pleasures",
    "When I grow up ...",
    "Can't make it to work today...",
    "Worst dates",
    "Monosyllabic",
    "Found in the basement",
    "Two line dialog: husband and wife",
    "Two line dialog: father and son",
    "Contacted at the seance",
    "Need counselling because...",
    "Pet peeves",
    "Where does your money go?",
    "Unusual birth control",
    "If I won the lottery",
    "What's that in the sky?",
    "Science gone awry",
    "Onomatopoeia",
    "Bad names for Mafia members",
    "Tourist traps",
    "What's for dinner?",
    "In-laws",
    "Strange health problems",
    "Lindsay Lohan biography title",
    "The \"Truth\" about Men",
    "The \"Truth\" about Women",
    "Awful ways to die",
    "Dieting",
    "Bad day at driving school",
    "The Bible",
    "Headlines",
    "Headlines we don't want to see",
    "Unusual pizza toppings",
    "Life as a secret agent",
    "Posted on YouTube",
    "In MY Day...",
    "Names for Santa's elves",
    "911. What's your emergency?",
    "Why isn't Santa coming this year?",
    "Literature",
    "Cartoons",
    "Dr. Phil guests",
    "Oprah's new game show",
    "Bad country song titles",
    "What to say to an ex",
    "Who is at your door?",
    "Movies",
    "Money",
    "Desk item(s)",
    "Body Parts",
    "A + B = C",
    "Book titles",
    "Awkward situation",
    "Create an Acro backwards",
    "Nightmare fuel",
    "Mythological creatures",
    "Morning Routine",
    "Lies parents tell their kids",
    "Why you can't be President",
    "My doctor told me",
    "Name your new business",
    "Redneck Christmas gifts",
    "He may be rich but...",
    "Europe",
    "Why they fired you",
    "Retro videogames",
    "Green things",
    "Signs you might be dead",
    "What I really want for Christmas",
    "If you could turn back time",
    "Found in Anne Frank's diary",
    "Jokes without a punchline",
    "Fun things to microwave",
    "Bad hospital names",
    "Rap lyrics",
    "What's in your lunchbox?",
    "Heard during childbirth",
    "Friends don't let friends...",
    "Animated TV shows",
    "Words of wisdom",
    "Bad racehorse names",
    "Rhyme an Acro backwards",
    "How to overcome shyness",
    "Make up a word and define it",
    "Your boss' deep dark secret",
    "Death bed confessions",
    "Parade mishaps",
    "Why isn't Hamburglar caught?",
    "Why you got a Nobel Prize",
    "Musical instruments",
    "__________. High five, bro.",
    "TSA guidelines now prohibit __________ on airplanes.",
    "It's a pity that kids these days are all getting involved with __________.",
    "In 1,000 years, when paper money is but a distant memory, __________ will be our currency.",
    "Major League Baseball has banned __________ for giving players an unfair advantage.",
    "What is Batman's guilty pleasure?",
    "Next from J.K. Rowling: Harry Potter and the Chamber of __________.",
    "I'm sorry, Professor, but I couldn't complete my homework because of __________.",
    "What did I bring back from Mexico?",
    "__________? There's an app for that.",
    "Betcha can't have just one!",
    "What's my anti-drug?",
    "While the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on __________.",
    "In the new Disney Channel Original Movie, Hannah Montana struggles with __________ for the first time.",
    "What's my secret power?",
    "What's the new fad diet?",
    "What did Vin Diesel eat for dinner?",
    "When Pharaoh remained unmoved, Moses called down a Plague of __________.",
    "How am I maintaining my relationship status?",
    "What's the crustiest?",
    "When I'm in prison, I'll have __________ smuggled in.",
    "After Hurricane Katrina, Sean Penn brought __________ to the people of New Orleans.",
    "Instead of coal, Santa now gives the bad children __________.",
    "Life was difficult for cavemen before __________.",
    "What's Teach for America using to inspire inner city students to succeed?",
    "Who stole the cookies from the cookie jar?",
    "In Michael Jackson's final moments, he thought about __________.",
    "White people like __________.",
    "Why do I hurt all over?",
    "A romantic candlelit dinner would be incomplete without __________.",
    "What will I bring back in time to convince people that I am a powerful wizard?",
    "BILLY MAYS HERE FOR __________.",
    "The class field trip was completely ruined by __________.",
    "What's a girl's best friend?",
    "I wish I hadn't lost the instruction manual for __________.",
    "When I am President of the United States, I will create the Department of __________.",
    "What are my parents hiding from me?",
    "What never fails to liven up the party?",
    "What gets better with age?",
    "__________: good to the last drop.",
    "I got 99 problems but __________ ain't one.",
    "It's a trap!",
    "MTV's new reality show features eight washed-up celebrities living with __________.",
    "What would grandma find disturbing, yet oddly charming?",
    "What's the most emo?",
    "During sex, I like to think about __________.",
    "What ended my last relationship?",
    "What's that sound?",
    "__________. That's how I want to die.",
    "Why am I sticky?",
    "What's the next Happy Meal® toy?",
    "What's there a ton of in heaven?",
    "I do not know with what weapons World War III will be fought, but World War IV will be fought with __________.",
    "What will always get you laid?",
    "__________: kid tested, mother approved.",
    "Why can't I sleep at night?",
    "What's that smell?",
    "What helps Obama unwind?",
    "This is the way the world ends  This is the way the world ends  Not with a bang but with __________.",
    "Coming to Broadway this season, __________: The Musical.",
    "Anthropologists have recently discovered a primitive tribe that worships __________.",
    "But before I kill you, Mr. Bond, I must show you __________.",
    "Studies show that lab rats navigate mazes 50% faster after being exposed to __________.",
    "Due to a PR fiasco, Walmart no longer offers __________.",
    "When I am a billionaire, I shall erect a 50-foot statue to commemorate __________.",
    "In an attempt to reach a wider audience, the Smithsonian Museum of Natural History has opened an interactive exhibit on __________.",
    "War! What is it good for?",
    "What gives me uncontrollable gas?",
    "What do old people smell like?",
    "Sorry everyone, I just __________.",
    "Alternative medicine is now embracing the curative powers of __________.",
    "The U.S. has begun airdropping __________ to the children of Afghanistan.",
    "What does Dick Cheney prefer?",
    "During Picasso's often-overlooked Brown Period, he produced hundreds of paintings of __________.",
    "What don't you want to find in your Chinese food?",
    "I drink to forget __________.",
    "What's the next superhero/sidekick duo?",
    "Things you find in your house after a party",
    "Wacky sports",
    "Celebrity news",
    "Film plot"
];